DROP TABLE INTREBARI;
DROP TABLE RASPUNSURI;
drop table teste;


CREATE TABLE INTREBARI (
  DOMENIU VARCHAR2(5),
  ID VARCHAR2(8) NOT NULL PRIMARY KEY,
  TEXT_INTREBARE VARCHAR2(1000) NOT NULL
)
/

CREATE TABLE RASPUNSURI(
  Q_ID VARCHAR2(8),
  ID VARCHAR2(8) NOT NULL PRIMARY KEY,
  TEXT_RASPUNS VARCHAR2(1000) NOT NULL,
  CORECT VARCHAR2(1) 
)
/

-- Domeniul 1 (geometrie)
INSERT INTO INTREBARI VALUES('D1','Q1','Care din urmatoarele figuri geometrice au 4 laturi ?');
INSERT INTO RASPUNSURI VALUES ('Q1','A1','Patrat','1');
INSERT INTO RASPUNSURI VALUES ('Q1','A2','Cerc','0');
INSERT INTO RASPUNSURI VALUES ('Q1','A3','Triunghi','0');
INSERT INTO RASPUNSURI VALUES ('Q1','A4','Romb','1');
INSERT INTO RASPUNSURI VALUES ('Q1','A5','Dreptunghi','1');
INSERT INTO RASPUNSURI VALUES ('Q1','A6','Paralelogram','1');
INSERT INTO RASPUNSURI VALUES ('Q1','A7','Hexagon','0');
INSERT INTO RASPUNSURI VALUES ('Q1','A8','Dodecagon','0');
INSERT INTO RASPUNSURI VALUES ('Q1','A9','Pentagon','0');
INSERT INTO RASPUNSURI VALUES ('Q1','A10','Poligon','0');

INSERT INTO INTREBARI VALUES('D1','Q2','Care din urmatoarele figuri geometrice au mai mult de 4 colturi ?');
INSERT INTO RASPUNSURI VALUES ('Q2','A11','Patrat','0');
INSERT INTO RASPUNSURI VALUES ('Q2','A12','Cerc','1');
INSERT INTO RASPUNSURI VALUES ('Q2','A13','Triunghi','0');
INSERT INTO RASPUNSURI VALUES ('Q2','A14','Romb','0');
INSERT INTO RASPUNSURI VALUES ('Q2','A15','Dreptunghi','0');
INSERT INTO RASPUNSURI VALUES ('Q2','A16','Paralelogram','0');
INSERT INTO RASPUNSURI VALUES ('Q2','A17','Hexagon','1');
INSERT INTO RASPUNSURI VALUES ('Q2','A18','Dodecagon','1');
INSERT INTO RASPUNSURI VALUES ('Q2','A19','Pentagon','1');
INSERT INTO RASPUNSURI VALUES ('Q2','A20','Poligon','0');

INSERT INTO INTREBARI VALUES('D1','Q3','Care din urmatoarele afirmatii sunt adevarate ?');
INSERT INTO RASPUNSURI VALUES ('Q3','A21','Triunghiul are 4 laturi','0');
INSERT INTO RASPUNSURI VALUES ('Q3','A22','Cercul are o infinitate de varfuri','1');
INSERT INTO RASPUNSURI VALUES ('Q3','A23','Suma unghiurilor unui triunghi este de 180 de grade','1');
INSERT INTO RASPUNSURI VALUES ('Q3','A24','Suma unghiurilor unui patrat este de 180 de grade','0');
INSERT INTO RASPUNSURI VALUES ('Q3','A25','Un patrat este un romb cu un unghi drept','1');
INSERT INTO RASPUNSURI VALUES ('Q3','A26','Un poligon este o linie franta inchisa','1');
INSERT INTO RASPUNSURI VALUES ('Q3','A27','Intr-un triunghi dreptunghic suma catetelor este egala cu ipotenuza','0');

INSERT INTO INTREBARI VALUES('D1','Q4','Care din urmatoarele figuri au toate laturile egale ?');
INSERT INTO RASPUNSURI VALUES ('Q4','A28','Triunghiul dreptunghic','0');
INSERT INTO RASPUNSURI VALUES ('Q4','A29','Triunghiul isoscel','0');
INSERT INTO RASPUNSURI VALUES ('Q4','A30','Triunghiul echilateral','1');
INSERT INTO RASPUNSURI VALUES ('Q4','A31','Patratul','1');
INSERT INTO RASPUNSURI VALUES ('Q4','A32','Rombul','1');
INSERT INTO RASPUNSURI VALUES ('Q4','A33','Dreptunghiul','0');
INSERT INTO RASPUNSURI VALUES ('Q4','A34','Hexagonul neregulat','0');

-- Domeniul 2 (numere)
INSERT INTO INTREBARI VALUES('D2','Q5','Care din urmatoarele sunt numere prime ?');
INSERT INTO RASPUNSURI VALUES ('Q5','A35','3','1');
INSERT INTO RASPUNSURI VALUES ('Q5','A36','7','1');
INSERT INTO RASPUNSURI VALUES ('Q5','A37','5','1');
INSERT INTO RASPUNSURI VALUES ('Q5','A38','13','1');
INSERT INTO RASPUNSURI VALUES ('Q5','A39','17','1');
INSERT INTO RASPUNSURI VALUES ('Q5','A40','9','0');
INSERT INTO RASPUNSURI VALUES ('Q5','A41','16','0');
INSERT INTO RASPUNSURI VALUES ('Q5','A42','22','0');
INSERT INTO RASPUNSURI VALUES ('Q5','A43','121','0');
INSERT INTO RASPUNSURI VALUES ('Q5','A44','14','0');

INSERT INTO INTREBARI VALUES('D2','Q6','Care din urmatoarele sunt numere pare ?');
INSERT INTO RASPUNSURI VALUES ('Q6','A45','2','1');
INSERT INTO RASPUNSURI VALUES ('Q6','A46','4','1');
INSERT INTO RASPUNSURI VALUES ('Q6','A47','6','1');
INSERT INTO RASPUNSURI VALUES ('Q6','A48','12','1');
INSERT INTO RASPUNSURI VALUES ('Q6','A49','100','1');
INSERT INTO RASPUNSURI VALUES ('Q6','A50','13','0');
INSERT INTO RASPUNSURI VALUES ('Q6','A51','15','0');
INSERT INTO RASPUNSURI VALUES ('Q6','A52','1','0');
INSERT INTO RASPUNSURI VALUES ('Q6','A53','7','0');
INSERT INTO RASPUNSURI VALUES ('Q6','A54','9','0');

INSERT INTO INTREBARI VALUES('D2','Q7','Care din urmatoarele numere sunt din sirul lui Fibonacci ?');
INSERT INTO RASPUNSURI VALUES ('Q7','A55','1','1');
INSERT INTO RASPUNSURI VALUES ('Q7','A56','2','1');
INSERT INTO RASPUNSURI VALUES ('Q7','A57','3','1');
INSERT INTO RASPUNSURI VALUES ('Q7','A58','5','1');
INSERT INTO RASPUNSURI VALUES ('Q7','A59','8','1');
INSERT INTO RASPUNSURI VALUES ('Q7','A60','13','1');
INSERT INTO RASPUNSURI VALUES ('Q7','A61','21','1');
INSERT INTO RASPUNSURI VALUES ('Q7','A62','22','0');
INSERT INTO RASPUNSURI VALUES ('Q7','A63','23','0');

-- Domeniul 3 (Flori)
INSERT INTO INTREBARI VALUES('D3','Q8','Care flori sunt sau pot fi albe ?');
INSERT INTO RASPUNSURI VALUES ('Q8','A64','Ghiocelul','1');
INSERT INTO RASPUNSURI VALUES ('Q8','A65','Margareta','1');
INSERT INTO RASPUNSURI VALUES ('Q8','A66','Trandafirul','1');
INSERT INTO RASPUNSURI VALUES ('Q8','A67','Floarea de soc','1');
INSERT INTO RASPUNSURI VALUES ('Q8','A68','Papadia','0');
INSERT INTO RASPUNSURI VALUES ('Q8','A69','Floarea de cires','1');
INSERT INTO RASPUNSURI VALUES ('Q8','A70','Crinul','1');
INSERT INTO RASPUNSURI VALUES ('Q8','A71','Bumbisorul','1');
INSERT INTO RASPUNSURI VALUES ('Q8','A72','Floarea soarelui','0');

INSERT INTO INTREBARI VALUES('D3','Q9','Care din urmatorele nume de fete sunt si nume de flori ?');
INSERT INTO RASPUNSURI VALUES ('Q9','A73','Crina','1');
INSERT INTO RASPUNSURI VALUES ('Q9','A74','Margareta','1');
INSERT INTO RASPUNSURI VALUES ('Q9','A75','Lacramioara','1');
INSERT INTO RASPUNSURI VALUES ('Q9','A76','Madalina','0');
INSERT INTO RASPUNSURI VALUES ('Q9','A77','Maria','0');
INSERT INTO RASPUNSURI VALUES ('Q9','A78','Larisa','0');
INSERT INTO RASPUNSURI VALUES ('Q9','A79','Georgiana','0');
INSERT INTO RASPUNSURI VALUES ('Q9','A80','Brandusa','1');
INSERT INTO RASPUNSURI VALUES ('Q9','A81','Ana','0');

-- Domeniul 4 (Teoria numerelor) 
INSERT INTO INTREBARI VALUES('D4','Q10','Cate litere are alfabetul roman?');
INSERT INTO RASPUNSURI VALUES ('Q10','A82',26,'0');
INSERT INTO RASPUNSURI VALUES ('Q10','A83',31,'1');
INSERT INTO RASPUNSURI VALUES ('Q10','A84','Ce e asta?','0');
INSERT INTO RASPUNSURI VALUES ('Q10','A85','26.5','0');
INSERT INTO RASPUNSURI VALUES ('Q10','A86','-12','0');
INSERT INTO RASPUNSURI VALUES ('Q10','A87','Pe toate.','0');

-- Domeniul 5 (Existentialism)
INSERT INTO INTREBARI VALUES('D5','Q11','Pe ce planeta traiesti?');
INSERT INTO RASPUNSURI VALUES ('Q11','A88','Pe pamant.','1');
INSERT INTO RASPUNSURI VALUES ('Q11','A89','Traiesc in nori.','0');
INSERT INTO RASPUNSURI VALUES ('Q11','A90','Pe juiter.','0');
INSERT INTO RASPUNSURI VALUES ('Q11','A91','Depinde.','0');
INSERT INTO RASPUNSURI VALUES ('Q11','A92','Pe luna.','0');
INSERT INTO RASPUNSURI VALUES ('Q11','A93','Pe toate.','0');

-- Domeniul 6 (Animale)
INSERT INTO INTREBARI VALUES('D6','Q12','Care animal este mamifer ?');
INSERT INTO RASPUNSURI VALUES ('Q12','A94','Ariciul','1');
INSERT INTO RASPUNSURI VALUES ('Q12','A95','Capra neagra','1');
INSERT INTO RASPUNSURI VALUES ('Q12','A96','Lupul','1');
INSERT INTO RASPUNSURI VALUES ('Q12','A97','Ursul','1');
INSERT INTO RASPUNSURI VALUES ('Q12','A98','Gaina','0');
INSERT INTO RASPUNSURI VALUES ('Q12','A99','Barza','0');
INSERT INTO RASPUNSURI VALUES ('Q12','A100','Sarpele','0');
INSERT INTO RASPUNSURI VALUES ('Q12','A101','Delfinul','1');
INSERT INTO RASPUNSURI VALUES ('Q12','A102','Broasca testoasa','0');

-- Domeniul 7 (Povesti)
INSERT INTO INTREBARI VALUES('D7','Q13','Cati pitici avea Cenusareasa ?');
INSERT INTO RASPUNSURI VALUES ('Q13','A103','0','1');
INSERT INTO RASPUNSURI VALUES ('Q13','A104','Niciunul','1');
INSERT INTO RASPUNSURI VALUES ('Q13','A105','1','0');
INSERT INTO RASPUNSURI VALUES ('Q13','A106','3','0');
INSERT INTO RASPUNSURI VALUES ('Q13','A107','7','0');
INSERT INTO RASPUNSURI VALUES ('Q13','A108','8','0');
INSERT INTO RASPUNSURI VALUES ('Q13','A109','Pe toti','0');
INSERT INTO RASPUNSURI VALUES ('Q13','A110','Unul si bun','0');
INSERT INTO RASPUNSURI VALUES ('Q13','A111','Nu stiu','0');

-- Domeniul 8 (Istorie)
INSERT INTO INTREBARI VALUES('D8','Q14','Cine a fost Alexandru Ioan Cuza ?');
INSERT INTO RASPUNSURI VALUES ('Q14','A112','a fost primul domnitor al Principatelor Unite si al statului national Romania','1');
INSERT INTO RASPUNSURI VALUES ('Q14','A113','un om inrobit de doua patimi Iubirea pentru patrie si cea pentru femei frumoase','1');
INSERT INTO RASPUNSURI VALUES ('Q14','A114','un om pasionat de cai','1');
INSERT INTO RASPUNSURI VALUES ('Q14','A115','un pictor roman','0');
INSERT INTO RASPUNSURI VALUES ('Q14','A116','primul scriitor de opera literara','0');
INSERT INTO RASPUNSURI VALUES ('Q14','A117','a fost ultimul domnitor al Principatelor Unite si al statului national Romania','0');
INSERT INTO RASPUNSURI VALUES ('Q14','A118','un domnitor roman nascut in anul 1820','1');
INSERT INTO RASPUNSURI VALUES ('Q14','A119','un domnitor roman nascut in anul 1859','0');
INSERT INTO RASPUNSURI VALUES ('Q14','A120','Domnitor in 1859-1866','1');

-- Domeniul 9 (Scriitori)
INSERT INTO INTREBARI VALUES('D9','Q15','Care este/sunt scriitori romani ?');
INSERT INTO RASPUNSURI VALUES ('Q15','A121','Mihai Eminescu','1');
INSERT INTO RASPUNSURI VALUES ('Q15','A122','Ion Luca Caragiale','1');
INSERT INTO RASPUNSURI VALUES ('Q15','A123','Mircea Cartarescu','1');
INSERT INTO RASPUNSURI VALUES ('Q15','A124','Mircea Eliade','1');
INSERT INTO RASPUNSURI VALUES ('Q15','A125','Ion Creanga','1');
INSERT INTO RASPUNSURI VALUES ('Q15','A126','Liviu Rebreanu','1');
INSERT INTO RASPUNSURI VALUES ('Q15','A127','Nicolae Grigorescu','0');
INSERT INTO RASPUNSURI VALUES ('Q15','A128','Nicolae Tonitza','0');
INSERT INTO RASPUNSURI VALUES ('Q15','A129','Stefan Luchian','0');
INSERT INTO RASPUNSURI VALUES ('Q15','A130','Ion Andreescu','0');

-- Domeniul 10 (Filme)
INSERT INTO INTREBARI VALUES('D10','Q16','Care dintre urmatoarele filme il au drept regizor pe Quentin Tarantino ?');
INSERT INTO RASPUNSURI VALUES ('Q16','A131','From Dusk till Dawn','1');
INSERT INTO RASPUNSURI VALUES ('Q16','A132','Pulp Fiction','1');
INSERT INTO RASPUNSURI VALUES ('Q16','A133','Django','1');
INSERT INTO RASPUNSURI VALUES ('Q16','A134','Eyes wide shut','0');
INSERT INTO RASPUNSURI VALUES ('Q16','A135','Terminator','0');
INSERT INTO RASPUNSURI VALUES ('Q16','A136','Godfather','0');
INSERT INTO RASPUNSURI VALUES ('Q16','A137','Kill Bill','1');
INSERT INTO RASPUNSURI VALUES ('Q16','A138','Ender’s Game','0');
INSERT INTO RASPUNSURI VALUES ('Q16','A139','Coboram la prima','0');
INSERT INTO RASPUNSURI VALUES ('Q16','A140','The Notebook','0');

-- Domeniul 11 (Geografie)
INSERT INTO INTREBARI VALUES('D11','Q17','Cu ce tari se invecineaza Romania?');
INSERT INTO RASPUNSURI VALUES ('Q17','A141','Ucraina','1');
INSERT INTO RASPUNSURI VALUES ('Q17','A142','Rusia','0');
INSERT INTO RASPUNSURI VALUES ('Q17','A143','Austria','0');
INSERT INTO RASPUNSURI VALUES ('Q17','A144','Ungaria','1');
INSERT INTO RASPUNSURI VALUES ('Q17','A145','Serbia','1');
INSERT INTO RASPUNSURI VALUES ('Q17','A146','Germania','0');
INSERT INTO RASPUNSURI VALUES ('Q17','A147','Bulgaria','1');
INSERT INTO RASPUNSURI VALUES ('Q17','A148','Republica Moldova','1');
INSERT INTO RASPUNSURI VALUES ('Q17','A149','Spania','0');
INSERT INTO RASPUNSURI VALUES ('Q17','A150','Macedonia','0');

-- Tot domeniul 5 (Existentialism)
INSERT INTO INTREBARI VALUES('D5','Q18','Care este raspunsul la orice intrebare de tip DA/NU?');
INSERT INTO RASPUNSURI VALUES ('Q18','A151','Tu ce crezi?','1');
INSERT INTO RASPUNSURI VALUES ('Q18','A152','Probabil.','1');
INSERT INTO RASPUNSURI VALUES ('Q18','A153','Nu stiu.','0');
INSERT INTO RASPUNSURI VALUES ('Q18','A154','Da.','0');
INSERT INTO RASPUNSURI VALUES ('Q18','A155','Nu.','0');
INSERT INTO RASPUNSURI VALUES ('Q18','A156','Depinde.','0');

--domeniul 7 povesti
INSERT INTO INTREBARI VALUES('D7','Q19','Cine a scris capra cu trei iezi? ');
INSERT INTO RASPUNSURI VALUES ('Q19','A157','Killa Fonic','0');
INSERT INTO RASPUNSURI VALUES ('Q19','A158','Ion Creanga','1');
INSERT INTO RASPUNSURI VALUES ('Q19','A159','Este povestire populara','0');
INSERT INTO RASPUNSURI VALUES ('Q19','A160','Vasile Alecsandri','0');
INSERT INTO RASPUNSURI VALUES ('Q19','A161','Cristian Tudor Popescu','0');
INSERT INTO RASPUNSURI VALUES ('Q19','A162','Mihail Sadoveanu','0');

-- domeniul 11 geografie
INSERT INTO INTREBARI VALUES('D11','Q20','Care tara este si continent?');
INSERT INTO RASPUNSURI VALUES('Q20', 'A163', 'Romania', '0');
INSERT INTO RASPUNSURI VALUES('Q20', 'A164', 'Australia', '1');
INSERT INTO RASPUNSURI VALUES('Q20', 'A165', 'Statele Unite ale Americii', '0');
INSERT INTO RASPUNSURI VALUES('Q20', 'A166', 'China', '0');
INSERT INTO RASPUNSURI VALUES('Q20', 'A167', 'Africa de Sud', '0');
INSERT INTO RASPUNSURI VALUES('Q20', 'A168', 'Rusia', '0');

--domeniul 9, scriitori
INSERT INTO INTREBARI VALUES('D9','Q21','Care din urmatoarele opere au fost scrise de Mircea Eliade?');
INSERT INTO RASPUNSURI VALUES('Q21','A169','Maitreyi','1');
INSERT INTO RASPUNSURI VALUES('Q21','A170','Romanul adolescentului miop','1');
INSERT INTO RASPUNSURI VALUES('Q21','A171','Noaptea de Sanziene','1');
INSERT INTO RASPUNSURI VALUES('Q21','A172','Domnisoara Christina','1');
INSERT INTO RASPUNSURI VALUES('Q21','A173','La tiganci','1');
INSERT INTO RASPUNSURI VALUES('Q21','A174','Pe culmile disperarii','0');
INSERT INTO RASPUNSURI VALUES('Q21','A175','Demiurgul cel rau','0');
INSERT INTO RASPUNSURI VALUES('Q21','A176','Despre neajunsul de a te fi nascut','0');

-- Domeniul 12 (Muzica)
INSERT INTO INTREBARI VALUES('D12','Q22','Care din urmatoarele sunt note muzicale valide ?');
INSERT INTO RASPUNSURI VALUES ('Q22','A177','Do','1');
INSERT INTO RASPUNSURI VALUES ('Q22','A178','Re','1');
INSERT INTO RASPUNSURI VALUES ('Q22','A179','Mi','1');
INSERT INTO RASPUNSURI VALUES ('Q22','A180','Fa','1');
INSERT INTO RASPUNSURI VALUES ('Q22','A181','Sol','1');
INSERT INTO RASPUNSURI VALUES ('Q22','A182','La','1');
INSERT INTO RASPUNSURI VALUES ('Q22','A183','Si','1');
INSERT INTO RASPUNSURI VALUES ('Q22','A184','Ri','0');
INSERT INTO RASPUNSURI VALUES ('Q22','A185','Mu','0');
INSERT INTO RASPUNSURI VALUES ('Q22','A186','Lo','0');

INSERT INTO INTREBARI VALUES('D12', 'Q24', 'Care dintre urmatorii artisti sunt francezi?');
INSERT INTO RASPUNSURI VALUES('Q24', 'A197', 'Stromae', '1');
INSERT INTO RASPUNSURI VALUES('Q24', 'A198', 'Indila', '1');
INSERT INTO RASPUNSURI VALUES('Q24', 'A199', 'Pomme', '1');
INSERT INTO RASPUNSURI VALUES('Q24', 'A200', 'Black M', '1');
INSERT INTO RASPUNSURI VALUES('Q24', 'A201', 'Eminem', '0');
INSERT INTO RASPUNSURI VALUES('Q24', 'A202', 'Illenium', '0');
INSERT INTO RASPUNSURI VALUES('Q24', 'A203', 'Billie Eilish', '0');
INSERT INTO RASPUNSURI VALUES('Q24', 'A204', 'Martin Garrix', '0');
INSERT INTO RASPUNSURI VALUES('Q24', 'A205', 'Alan Walker', '0');
INSERT INTO RASPUNSURI VALUES('Q24', 'A206', 'Faruko', '0');

--Tot domeniul 9 (Scriitori)
INSERT INTO INTREBARI VALUES ('D9','Q23','Care dintre urmatoarele poezii sunt scrise de Mihai Eminescu?');
INSERT INTO RASPUNSURI VALUES('Q23','A187','Floare albastra','1');
INSERT INTO RASPUNSURI VALUES('Q23','A188','Luceafarul','1');
INSERT INTO RASPUNSURI VALUES('Q23','A189','Iarna pe ulita','0');
INSERT INTO RASPUNSURI VALUES('Q23','A190','Somnoroase pasarele','1');
INSERT INTO RASPUNSURI VALUES('Q23','A191','Plumb','0');
INSERT INTO RASPUNSURI VALUES('Q23','A192','Si daca...','1');
INSERT INTO RASPUNSURI VALUES('Q23','A193','Testament','0');
INSERT INTO RASPUNSURI VALUES('Q23','A194','Acceleratul','0');
INSERT INTO RASPUNSURI VALUES('Q23','A195','De pe-o buna dimineata','0');
INSERT INTO RASPUNSURI VALUES('Q23','A196','Rapsodii de toamna','0');

--Domeniul 13 TIC:
INSERT INTO INTREBARI VALUES('D13', 'Q25', 'Care dintre urmatoarele sunt dispozitive periferice de iesire?');
INSERT INTO RASPUNSURI VALUES('Q25', 'A207', 'Tastatura', '0');
INSERT INTO RASPUNSURI VALUES('Q25', 'A208', 'Imprimanta', '1');
INSERT INTO RASPUNSURI VALUES('Q25', 'A209', 'Difuzor', '1');
INSERT INTO RASPUNSURI VALUES('Q25', 'A210', 'Mouse', '0');
INSERT INTO RASPUNSURI VALUES('Q25', 'A211', 'Microfon', '0');
INSERT INTO RASPUNSURI VALUES('Q25', 'A212', 'Monitor', '1');
INSERT INTO RASPUNSURI VALUES('Q25', 'A213', 'Camera video', '0');
INSERT INTO RASPUNSURI VALUES('Q25', 'A214', 'Plotter', '1');
INSERT INTO RASPUNSURI VALUES('Q25', 'A215', 'Trackball', '0');
INSERT INTO RASPUNSURI VALUES('Q25', 'A216', 'Scanner', '0');

--Domeniul 14 Informatica:
INSERT INTO INTREBARI VALUES('D14', 'Q26', 'Care dintre urmatoarele tipuri de sortare au o complexitate medie O(n*log(n))?');
INSERT INTO RASPUNSURI VALUES('Q26', 'A217', 'Bubble Sort', '0');
INSERT INTO RASPUNSURI VALUES('Q26', 'A218', 'Quick Sort', '1');
INSERT INTO RASPUNSURI VALUES('Q26', 'A219', 'Insertion Sort', '0');
INSERT INTO RASPUNSURI VALUES('Q26', 'A220', 'Heap Sort', '1');
INSERT INTO RASPUNSURI VALUES('Q26', 'A221', 'Merge Sort', '1');
INSERT INTO RASPUNSURI VALUES('Q26', 'A222', 'Bucket Sort', '0');
INSERT INTO RASPUNSURI VALUES('Q26', 'A223', 'Selection Sort', '0');

INSERT INTO INTREBARI VALUES('D14', 'Q27', 'Care dintre urmatoarele raspunsuri sunt limbaje de programare?');
INSERT INTO RASPUNSURI VALUES('Q27', 'A224', 'HTML', '0');
INSERT INTO RASPUNSURI VALUES('Q27', 'A225', 'C', '1');
INSERT INTO RASPUNSURI VALUES('Q27', 'A226', 'CSS', '0');
INSERT INTO RASPUNSURI VALUES('Q27', 'A227', 'Java', '1');
INSERT INTO RASPUNSURI VALUES('Q27', 'A228', 'C#', '1');
INSERT INTO RASPUNSURI VALUES('Q27', 'A229', 'C++', '1');
INSERT INTO RASPUNSURI VALUES('Q27', 'A230', 'Python', '1');
INSERT INTO RASPUNSURI VALUES('Q27', 'A231', 'Semnelor', '0');
INSERT INTO RASPUNSURI VALUES('Q27', 'A232', 'Autostopul', '0');

INSERT INTO INTREBARI VALUES('D14','Q28','Care dintre variante reprezinta un cuvant intalnit des din domeniul informaticii?');
INSERT INTO RASPUNSURI VALUES ('Q28','A233','Byte','1');
INSERT INTO RASPUNSURI VALUES ('Q28','A234','Eroare','1');
INSERT INTO RASPUNSURI VALUES ('Q28','A235','Aplicatie','1');
INSERT INTO RASPUNSURI VALUES ('Q28','A236','Spatiu','1');
INSERT INTO RASPUNSURI VALUES ('Q28','A237','Timp','1');
INSERT INTO RASPUNSURI VALUES ('Q28','A238','Volum','0');
INSERT INTO RASPUNSURI VALUES ('Q28','A239','Acid Ribonucleic','0');
INSERT INTO RASPUNSURI VALUES ('Q28','A240','Restanta','0');
INSERT INTO RASPUNSURI VALUES ('Q28','A241','Arsen','0');
INSERT INTO RASPUNSURI VALUES ('Q28','A242','Impedanta','0');

INSERT INTO INTREBARI VALUES('D14','Q29','Care este maestrul xiaolin?');
INSERT INTO RASPUNSURI VALUES ('Q29','A243','Omni','1');
INSERT INTO RASPUNSURI VALUES ('Q29','A244','Kai','1');
INSERT INTO RASPUNSURI VALUES ('Q29','A245','Raimundo','1');
INSERT INTO RASPUNSURI VALUES ('Q29','A246','Kimiko','1');
INSERT INTO RASPUNSURI VALUES ('Q29','A247','Wuya','0');
INSERT INTO RASPUNSURI VALUES ('Q29','A248','Jack','0');
INSERT INTO RASPUNSURI VALUES ('Q29','A249','Chase','0');
INSERT INTO RASPUNSURI VALUES ('Q29','A250','Master Fung','0');
INSERT INTO RASPUNSURI VALUES ('Q29','A251','IDK','0');
INSERT INTO RASPUNSURI VALUES ('Q29','A252','Bruce Lee','0');

-- Domeniul 10 FILME
INSERT INTO INTREBARI VALUES('D10','Q30','Ce personaje au murit Avengers: Endgame?');
INSERT INTO RASPUNSURI VALUES ('Q30','A301','Black Widow','1');
INSERT INTO RASPUNSURI VALUES ('Q30','A302','Tony Stark','1');
INSERT INTO RASPUNSURI VALUES ('Q30','A303','Hawkeye','0');
INSERT INTO RASPUNSURI VALUES ('Q30','A304','Captain America','0');
INSERT INTO RASPUNSURI VALUES ('Q30','A305','Scarlet Witch','0');
INSERT INTO RASPUNSURI VALUES ('Q30','A306','Roket','0');
INSERT INTO RASPUNSURI VALUES ('Q30','A307','Gamora','0');
INSERT INTO RASPUNSURI VALUES ('Q30','A308','Spider man','0');
INSERT INTO RASPUNSURI VALUES ('Q30','A309','IDK','0');
INSERT INTO RASPUNSURI VALUES ('Q30','A310','Thanos','1');

--Domeniul 15 Astronomie
INSERT INTO INTREBARI VALUES('D15','Q31','Care dintre urmatoarele planete efectueaza o miscare retrograda?');
INSERT INTO RASPUNSURI VALUES ('Q31','A311','Mercur','0');
INSERT INTO RASPUNSURI VALUES ('Q31','A312','Venus','1');
INSERT INTO RASPUNSURI VALUES ('Q31','A313','Pamant','0');
INSERT INTO RASPUNSURI VALUES ('Q31','A314','Marte','0');
INSERT INTO RASPUNSURI VALUES ('Q31','A315','Jupiter','0');
INSERT INTO RASPUNSURI VALUES ('Q31','A316','Saturn','0');
INSERT INTO RASPUNSURI VALUES ('Q31','A317','Uranus','1');
INSERT INTO RASPUNSURI VALUES ('Q31','A318','Neptun','0');
INSERT INTO RASPUNSURI VALUES ('Q31','A319','Pluto','1');

-- Domeniul 14 (Informatica)
INSERT INTO INTREBARI VALUES ('D14','Q32','Care dintre urmatoarele sisteme de baze de date sunt relationale?');
INSERT INTO RASPUNSURI VALUES ('Q32','A320','PostgreSQL','1');
INSERT INTO RASPUNSURI VALUES ('Q32','A321','Microsoft SQL Server','1');
INSERT INTO RASPUNSURI VALUES ('Q32','A322','Microsoft Azure SQL','1');
INSERT INTO RASPUNSURI VALUES ('Q32','A323','Apache CouchDB','0');
INSERT INTO RASPUNSURI VALUES ('Q32','A324','Redis','0');
INSERT INTO RASPUNSURI VALUES ('Q32','A325','MongoDB','0');
INSERT INTO RASPUNSURI VALUES ('Q32','A326','SQLite','1');
INSERT INTO RASPUNSURI VALUES ('Q32','A327','Cassandra','0');
INSERT INTO RASPUNSURI VALUES ('Q32','A328','HBase','0');
INSERT INTO RASPUNSURI VALUES ('Q32','A329','MariaDB','1');

-- Domeniul 14 (Informatica)
INSERT INTO INTREBARI VALUES ('D14','Q33','Care dintre urmatoarele este un sistem de operare?');
INSERT INTO RASPUNSURI VALUES ('Q33','A330','Windows','1');
INSERT INTO RASPUNSURI VALUES ('Q33','A331','MD-DOS','1');
INSERT INTO RASPUNSURI VALUES ('Q33','A332','Ubuntu','1');
INSERT INTO RASPUNSURI VALUES ('Q33','A333','HTML','0');
INSERT INTO RASPUNSURI VALUES ('Q33','A334','USB','0');
INSERT INTO RASPUNSURI VALUES ('Q33','A335','JVM','0');
INSERT INTO RASPUNSURI VALUES ('Q33','A336','TempleOS','1');
INSERT INTO RASPUNSURI VALUES ('Q33','A337','BananaOS','0');
INSERT INTO RASPUNSURI VALUES ('Q33','A338','Antena 5G','0');
INSERT INTO RASPUNSURI VALUES ('Q33','A339','MacOS','1');

-- Domeniul 14 (Informatica)
INSERT INTO INTREBARI VALUES ('D14','Q34','Cine a inventat Git?');
INSERT INTO RASPUNSURI VALUES ('Q34','A340','Linus Torvalds','1');
INSERT INTO RASPUNSURI VALUES ('Q34','A341','Bill Gates','0');
INSERT INTO RASPUNSURI VALUES ('Q34','A342','Dennis Ritchie','0');
INSERT INTO RASPUNSURI VALUES ('Q34','A343','RMS','0');
INSERT INTO RASPUNSURI VALUES ('Q34','A344','Microsoft','0');
INSERT INTO RASPUNSURI VALUES ('Q34','A345','Github','0');

--Tot domeniul 12 (muzica)
INSERT INTO INTREBARI VALUES('D12', 'Q35', 'Care dintre urmatoarele sunt titluri de albume solo Michael Jackson?');
INSERT INTO RASPUNSURI VALUES('Q35', 'A346', 'Bad', '1');
INSERT INTO RASPUNSURI VALUES('Q35', 'A347', 'Good', '0');
INSERT INTO RASPUNSURI VALUES('Q35', 'A348', 'Ben', '1');
INSERT INTO RASPUNSURI VALUES('Q35', 'A349', 'Innervisions', '0');
INSERT INTO RASPUNSURI VALUES('Q35', 'A350', 'The White Album', '0');
INSERT INTO RASPUNSURI VALUES('Q35', 'A351', 'Dangerous', '1');
INSERT INTO RASPUNSURI VALUES('Q35', 'A352', 'Life After Death', '0');
INSERT INTO RASPUNSURI VALUES('Q35', 'A353', 'Invincible', '1');
INSERT INTO RASPUNSURI VALUES('Q35', 'A354', 'Victory', '0');
INSERT INTO RASPUNSURI VALUES('Q35', 'A355', 'My Life', '0');

-- tot domeniul 14 (informatica)
INSERT INTO INTREBARI VALUES ('D14', 'Q36', 'Care dintre urmatoarele NU sunt distributii de Linux?');
INSERT INTO RASPUNSURI VALUES ('Q36', 'A356', 'Arch Linux', 0);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A357', 'Void Linux', 0);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A358', 'Linux Cinnamon', 1);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A359', 'Linux Mint', 0);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A360', 'Pop!_OS', 0);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A361', 'Red Hat Linux', 0);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A362', 'Black Hat Linux', 1);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A363', 'White Hat Linux', 1);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A364', 'Ubuntu', 0);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A365', 'Kubuntu', 0);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A366', 'Lubuntu', 0);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A367', 'Xubuntu', 0);
INSERT INTO RASPUNSURI VALUES ('Q36', 'A368', 'Nubuntu', 1);

-- DOMENIUL 16 BIOLOGIE
INSERT INTO INTREBARI VALUES('D16','Q37','Ce organit celular este supra-numit <The powerhouse of the cell>?');
INSERT INTO RASPUNSURI VALUES('Q37', 'A369', 'Mitocondria', '1');
INSERT INTO RASPUNSURI VALUES('Q37', 'A370', 'Mitocendria', '0');
INSERT INTO RASPUNSURI VALUES('Q37', 'A371', 'Mitucondria', '0');
INSERT INTO RASPUNSURI VALUES('Q37', 'A372', 'Mitocondriul', '0');
INSERT INTO RASPUNSURI VALUES('Q37', 'A373', 'Nucleul', '0');
INSERT INTO RASPUNSURI VALUES('Q37', 'A374', 'Ribozomul', '0');
INSERT INTO RASPUNSURI VALUES('Q37', 'A375', 'Aparatul Golgi', '0');
INSERT INTO RASPUNSURI VALUES('Q37', 'A376', 'Mitocondria, din nou', '1');

-- DOMENIUL 14&5
INSERT INTO INTREBARI VALUES('D14','Q38','Care dintre urmatoarele secvente de cod descrie starea mintala a unui student la informatica?');
INSERT INTO RASPUNSURI VALUES('Q38', 'A377', 'for( ;_; ){ cry(); }', '1');
INSERT INTO RASPUNSURI VALUES('Q38', 'A378', ':(){ :|: & };:', '1');
INSERT INTO RASPUNSURI VALUES('Q38', 'A379', '?(*’?’*)/', '0');
INSERT INTO RASPUNSURI VALUES('Q38', 'A380', '}:-)', '0');
INSERT INTO RASPUNSURI VALUES('Q38', 'A381', '>.<', '0');
INSERT INTO RASPUNSURI VALUES('Q38', 'A382', '??|?|?? ?|?|??', '0');
INSERT INTO RASPUNSURI VALUES('Q38', 'A383', '?(´???? )???°', '0');
COMMIT;

-- DOMENIUL 14
INSERT INTO INTREBARI VALUES('D14','Q39','Cate puncte aveti la PSGBD pana acum?');
INSERT INTO RASPUNSURI VALUES('Q39', 'A384', 'nu stim', '1');
INSERT INTO RASPUNSURI VALUES('Q39', 'A385', '0-10', '0');
INSERT INTO RASPUNSURI VALUES('Q39', 'A386', '11-20', '0');
INSERT INTO RASPUNSURI VALUES('Q39', 'A387', '21-30', '0');
INSERT INTO RASPUNSURI VALUES('Q39', 'A388', '31-40', '0');
INSERT INTO RASPUNSURI VALUES('Q39', 'A389', '41-50', '0');
INSERT INTO RASPUNSURI VALUES('Q39', 'A390', '50+', '0');

--DOMENIUL 17 CULORI
INSERT INTO INTREBARI VALUES('D17','Q40','Care dintre urmatoarele sunt culori care nu sunt primare?');
INSERT INTO RASPUNSURI VALUES('Q40', 'A391', 'verde', '1');
INSERT INTO RASPUNSURI VALUES('Q40', 'A392', 'rosu', '0');
INSERT INTO RASPUNSURI VALUES('Q40', 'A393', 'gri', '0');
INSERT INTO RASPUNSURI VALUES('Q40', 'A394', 'indigo', '1');
INSERT INTO RASPUNSURI VALUES('Q40', 'A395', 'albastru', '0');
INSERT INTO RASPUNSURI VALUES('Q40', 'A396', 'oranj', '1');
INSERT INTO RASPUNSURI VALUES('Q40', 'A397', 'galben', '0');

--DOMENIUL 17 CULORI
INSERT INTO INTREBARI VALUES('D17','Q41','Care dintre urmatoarele culori sunt nuante de roz?');
INSERT INTO RASPUNSURI VALUES('Q41', 'A398', 'MediumVioletRed', '1');
INSERT INTO RASPUNSURI VALUES('Q41', 'A399', 'RosyBrown', '0');
INSERT INTO RASPUNSURI VALUES('Q41', 'A400', 'Fuchsia', '0');
INSERT INTO RASPUNSURI VALUES('Q41', 'A401', 'HotPink', '1');
INSERT INTO RASPUNSURI VALUES('Q41', 'A402', 'Thistle', '0');
INSERT INTO RASPUNSURI VALUES('Q41', 'A403', 'PaleVioletRed', '1');
INSERT INTO RASPUNSURI VALUES('Q41', 'A404', 'LightCoral ', '0');

--DOMENIUL 18 WEB
INSERT INTO INTREBARI VALUES ('D18', 'Q42', 'Ce este CORS, si ce efect are o exceptie de acest tip asupra unui request ?');
INSERT INTO RASPUNSURI VALUES('Q42', 'A405', 'CROSS ORIGIN ACESS si previne un client din a face request catre un server pe un port diferit',   '1');
INSERT INTO RASPUNSURI VALUES('Q42', 'A406', 'CROASSANT OREO SECURIZAT  si este un warning care specifica ca requestul nu are sens.',           '0');
INSERT INTO RASPUNSURI VALUES('Q42', 'A407', 'CORD ORIGIN ACESS si e o exceptie care previne atacatorii din a fura date',                       '0');
INSERT INTO RASPUNSURI VALUES('Q42', 'A408', 'CROSS ORIGIN ACESS si spune browserelor sa faca request catre aceiasi origine',                   '1');
INSERT INTO RASPUNSURI VALUES('Q42', 'A409', 'CROSS ORIGIN ACESS si previne aplicatiile externe din a folosit un request',                      '1');
INSERT INTO RASPUNSURI VALUES('Q42', 'A410', 'CROSS ORIGIN ACESS si nu are nici un efect asupra unui request',                                  '0');
INSERT INTO RASPUNSURI VALUES('Q42', 'A411', 'Este un protocol HTTP foarte bine securizat, care trimite datele dintrun request encodate',       '0');

--DOMENIUL 19 MATEMATICA
INSERT INTO INTREBARI VALUES ('D19', 'Q43', 'Cat e  0/0 ?');
INSERT INTO RASPUNSURI VALUES('Q43', 'A412', 'NaN', '1');
INSERT INTO RASPUNSURI VALUES('Q43', 'A413', 'undefined',   '1');
INSERT INTO RASPUNSURI VALUES('Q43', 'A414', 'null',   '1');
INSERT INTO RASPUNSURI VALUES('Q43', 'A415', 'eroare',   '1');
INSERT INTO RASPUNSURI VALUES('Q43', 'A416', '0',   '0');
INSERT INTO RASPUNSURI VALUES('Q43', 'A417', '1',   '0');
INSERT INTO RASPUNSURI VALUES('Q43', 'A418', 'infinit',   '0');
INSERT INTO RASPUNSURI VALUES('Q43', 'A419', '2',   '0');
INSERT INTO RASPUNSURI VALUES('Q43', 'A420', '-1',   '0');
INSERT INTO RASPUNSURI VALUES('Q43', 'A421', '-0',   '0');

INSERT INTO INTREBARI VALUES ('D19', 'Q44', 'Cat e 1978.2/0.1 ?');
INSERT INTO RASPUNSURI VALUES('Q44', 'A422', '22', '0');
INSERT INTO RASPUNSURI VALUES('Q44', 'A423', '0', '0');
INSERT INTO RASPUNSURI VALUES('Q44', 'A424', '-1',   '0');
INSERT INTO RASPUNSURI VALUES('Q44', 'A425', '4',   '0');
INSERT INTO RASPUNSURI VALUES('Q44', 'A426', '19.78',   '1');
INSERT INTO RASPUNSURI VALUES('Q44', 'A427', '5',   '0');
INSERT INTO RASPUNSURI VALUES('Q44', 'A428', '2',   '0');
INSERT INTO RASPUNSURI VALUES('Q44', 'A429', '19',   '0');
INSERT INTO RASPUNSURI VALUES('Q44', 'A430', '-19',   '0');
INSERT INTO RASPUNSURI VALUES('Q44', 'A431', '20',   '0');

INSERT INTO INTREBARI VALUES ('D19','Q45', 'Cu cat este egal 3 la p?trat ?');
INSERT INTO RASPUNSURI VALUES('Q45', 'A432', '2',   '0');
INSERT INTO RASPUNSURI VALUES('Q45', 'A433', '4',   '0');
INSERT INTO RASPUNSURI VALUES('Q45', 'A434', '9',   '1');
INSERT INTO RASPUNSURI VALUES('Q45', 'A435', '3',   '0');
INSERT INTO RASPUNSURI VALUES('Q45', 'A436', '-3',   '0');
INSERT INTO RASPUNSURI VALUES('Q45', 'A437', '6',   '0');
INSERT INTO RASPUNSURI VALUES('Q45', 'A438', '5',   '0');
INSERT INTO RASPUNSURI VALUES('Q45', 'A439', '10',   '0');
INSERT INTO RASPUNSURI VALUES('Q45', 'A440', '33',   '0');
INSERT INTO RASPUNSURI VALUES('Q45', 'A441', '100',   '0');

-- DOMENIUL 15 ASTRONOMIE
INSERT INTO INTREBARI VALUES ('D15','Q46', 'Care este prima planeta de la soare?');
INSERT INTO RASPUNSURI VALUES('Q46', 'A442', 'Terra',   '0');
INSERT INTO RASPUNSURI VALUES('Q46', 'A443', 'Marte',   '0');
INSERT INTO RASPUNSURI VALUES('Q46', 'A444', 'Mercur',   '1');
INSERT INTO RASPUNSURI VALUES('Q46', 'A445', 'Ceres',   '0');
INSERT INTO RASPUNSURI VALUES('Q46', 'A446', 'Pluto',   '0');
INSERT INTO RASPUNSURI VALUES('Q46', 'A447', 'Saturn',   '0');
INSERT INTO RASPUNSURI VALUES('Q46', 'A448', 'Uranus',   '0');
INSERT INTO RASPUNSURI VALUES('Q46', 'A449', 'Neptun',   '0');
INSERT INTO RASPUNSURI VALUES('Q46', 'A450', 'Luna',   '0');
INSERT INTO RASPUNSURI VALUES('Q46', 'A451', 'Soarele',   '0');

INSERT INTO INTREBARI VALUES ('D15', 'Q47', 'Cati sateliti naturali are planeta Pamant?');
INSERT INTO RASPUNSURI VALUES ('Q47', 'A452', '2', '0');
INSERT INTO RASPUNSURI VALUES ('Q47', 'A453', '0', '0');
INSERT INTO RASPUNSURI VALUES ('Q47', 'A454', '4', '0');
INSERT INTO RASPUNSURI VALUES ('Q47', 'A455', '1', '1');
INSERT INTO RASPUNSURI VALUES ('Q47', 'A456', '3', '0');
INSERT INTO RASPUNSURI VALUES ('Q47', 'A457', '10', '0');
INSERT INTO RASPUNSURI VALUES ('Q47', 'A458', '5', '0');
INSERT INTO RASPUNSURI VALUES ('Q47', 'A459', '8', '0');

--DOMENIU 20 fizica 
INSERT INTO INTREBARI VALUES ('D20', 'Q48', 'Care este rezistanta grup?rii în serie a 3 rezisten?e de 12 ohmi?');
INSERT INTO RASPUNSURI VALUES ('Q48', 'A460', '10', '0');
INSERT INTO RASPUNSURI VALUES ('Q48', 'A461', '5', '0');
INSERT INTO RASPUNSURI VALUES ('Q48', 'A462', '3.3', '0');
INSERT INTO RASPUNSURI VALUES ('Q48', 'A463', '20', '0');
INSERT INTO RASPUNSURI VALUES ('Q48', 'A464', '15', '0');
INSERT INTO RASPUNSURI VALUES ('Q48', 'A465', '24', '0');
INSERT INTO RASPUNSURI VALUES ('Q48', 'A466', '36', '1');
INSERT INTO RASPUNSURI VALUES ('Q48', 'A467', '12.5', '0');
INSERT INTO RASPUNSURI VALUES ('Q48', 'A468', '7.5', '0');
INSERT INTO RASPUNSURI VALUES ('Q48', 'A469', '1', '0');

INSERT INTO INTREBARI VALUES ('D20', 'Q49', 'Care este rezistanta grup?rii în paralel a 3 rezisten?e de 12 ohmi?');
INSERT INTO RASPUNSURI VALUES ('Q49', 'A470', '10', '0');
INSERT INTO RASPUNSURI VALUES ('Q49', 'A471', '5', '0');
INSERT INTO RASPUNSURI VALUES ('Q49', 'A472', '4', '1');
INSERT INTO RASPUNSURI VALUES ('Q49', 'A473', '20', '0');
INSERT INTO RASPUNSURI VALUES ('Q49', 'A474', '15', '0');
INSERT INTO RASPUNSURI VALUES ('Q49', 'A475', '25', '0');
INSERT INTO RASPUNSURI VALUES ('Q49', 'A476', '30', '0');
INSERT INTO RASPUNSURI VALUES ('Q49', 'A477', '12.5', '0');
INSERT INTO RASPUNSURI VALUES ('Q49', 'A478', '7.5', '0');
INSERT INTO RASPUNSURI VALUES ('Q49', 'A479', '3.3', '0');

INSERT INTO INTREBARI VALUES ('D20', 'Q50', 'Care sunt unit??i de m?sur? a curentului electric?');
INSERT INTO RASPUNSURI VALUES ('Q50', 'A480', 'A', '1');
INSERT INTO RASPUNSURI VALUES ('Q50', 'A481', 'mA', '1');
INSERT INTO RASPUNSURI VALUES ('Q50', 'A482', 'kA', '1');
INSERT INTO RASPUNSURI VALUES ('Q50', 'A483', 'V', '0');
INSERT INTO RASPUNSURI VALUES ('Q50', 'A484', 'mV', '0');
INSERT INTO RASPUNSURI VALUES ('Q50', 'A485', 'kV', '0');
INSERT INTO RASPUNSURI VALUES ('Q50', 'A486', 'F', '0');
INSERT INTO RASPUNSURI VALUES ('Q50', 'A487', 'mF', '0');
INSERT INTO RASPUNSURI VALUES ('Q50', 'A488', 'H', '0');
INSERT INTO RASPUNSURI VALUES ('Q50', 'A489', 'mH', '0');

INSERT INTO INTREBARI VALUES ('D20', 'Q51', 'Care sunt unit??i de m?sur? a tensiunii electrice?');
INSERT INTO RASPUNSURI VALUES ('Q51', 'A490', 'A', '0');
INSERT INTO RASPUNSURI VALUES ('Q51', 'A491', 'mA', '0');
INSERT INTO RASPUNSURI VALUES ('Q51', 'A492', 'kA', '0');
INSERT INTO RASPUNSURI VALUES ('Q51', 'A493', 'V', '1');
INSERT INTO RASPUNSURI VALUES ('Q51', 'A494', 'mV', '1');
INSERT INTO RASPUNSURI VALUES ('Q51', 'A495', 'kV', '1');
INSERT INTO RASPUNSURI VALUES ('Q51', 'A496', 'F', '0');
INSERT INTO RASPUNSURI VALUES ('Q51', 'A497', 'mF', '0');
INSERT INTO RASPUNSURI VALUES ('Q51', 'A498', 'H', '0');
INSERT INTO RASPUNSURI VALUES ('Q51', 'A499', 'mH', '0');

INSERT INTO INTREBARI VALUES ('D20', 'Q52', 'Care sunt unit??i de m?sur? a puterii?');
INSERT INTO RASPUNSURI VALUES ('Q52', 'A579', 'V', '0');
INSERT INTO RASPUNSURI VALUES ('Q52', 'A580', 'A', '0');
INSERT INTO RASPUNSURI VALUES ('Q52', 'A581', 'W', '1');
INSERT INTO RASPUNSURI VALUES ('Q52', 'A582', 'Kg', '0');
INSERT INTO RASPUNSURI VALUES ('Q52', 'A583', 'secunde', '0');
INSERT INTO RASPUNSURI VALUES ('Q52', 'A584', 'kW', '1');
INSERT INTO RASPUNSURI VALUES ('Q52', 'A585', 'F', '0');
INSERT INTO RASPUNSURI VALUES ('Q52', 'A586', 'mF', '0');
INSERT INTO RASPUNSURI VALUES ('Q52', 'A587', 'H', '0');
INSERT INTO RASPUNSURI VALUES ('Q52', 'A588', 'mH', '0');

INSERT INTO INTREBARI VALUES ('D20', 'Q53', 'Care sunt unit??ile de m?sur? a condensatorului?');
INSERT INTO RASPUNSURI VALUES ('Q53', 'A500', 'A', '0');
INSERT INTO RASPUNSURI VALUES ('Q53', 'A501', 'mA', '0');
INSERT INTO RASPUNSURI VALUES ('Q53', 'A502', 'kA', '0');
INSERT INTO RASPUNSURI VALUES ('Q53', 'A503', 'V', '0');
INSERT INTO RASPUNSURI VALUES ('Q53', 'A504', 'mV', '0');
INSERT INTO RASPUNSURI VALUES ('Q53', 'A505', 'kV', '0');
INSERT INTO RASPUNSURI VALUES ('Q53', 'A506', 'F', '1');
INSERT INTO RASPUNSURI VALUES ('Q53', 'A507', 'mF', '1');
INSERT INTO RASPUNSURI VALUES ('Q53', 'A508', 'H', '0');
INSERT INTO RASPUNSURI VALUES ('Q53', 'A509', 'mH', '0');

INSERT INTO INTREBARI VALUES ('D20', 'Q54', 'Care sunt unit??ile de m?sur? a inductorului (bobina)?');
INSERT INTO RASPUNSURI VALUES ('Q54', 'A510', 'A', '0');
INSERT INTO RASPUNSURI VALUES ('Q54', 'A511', 'mA', '0');
INSERT INTO RASPUNSURI VALUES ('Q54', 'A512', 'kA', '0');
INSERT INTO RASPUNSURI VALUES ('Q54', 'A513', 'V', '0');
INSERT INTO RASPUNSURI VALUES ('Q54', 'A514', 'mV', '0');
INSERT INTO RASPUNSURI VALUES ('Q54', 'A515', 'kV', '0');
INSERT INTO RASPUNSURI VALUES ('Q54', 'A516', 'F', '0');
INSERT INTO RASPUNSURI VALUES ('Q54', 'A517', 'mF', '0');
INSERT INTO RASPUNSURI VALUES ('Q54', 'A518', 'H', '1');
INSERT INTO RASPUNSURI VALUES ('Q54', 'A519', 'mH', '1');

INSERT INTO INTREBARI VALUES ('D20', 'Q55', 'Care este curentul printr-un rezistor de 1kOhm care are la borne tensiunea de 10V?');
INSERT INTO RASPUNSURI VALUES ('Q55', 'A520', '0.01A', '0');
INSERT INTO RASPUNSURI VALUES ('Q55', 'A521', '0.1A', '1');
INSERT INTO RASPUNSURI VALUES ('Q55', 'A522', '1A', '0');
INSERT INTO RASPUNSURI VALUES ('Q55', 'A523', '0.1mA', '0');
INSERT INTO RASPUNSURI VALUES ('Q55', 'A524', '1mA', '0');
INSERT INTO RASPUNSURI VALUES ('Q55', 'A525', '10mA', '0');
INSERT INTO RASPUNSURI VALUES ('Q55', 'A526', '100mA', '1');
INSERT INTO RASPUNSURI VALUES ('Q55', 'A527', 'mF', '0');
INSERT INTO RASPUNSURI VALUES ('Q55', 'A528', 'H', '0');
INSERT INTO RASPUNSURI VALUES ('Q55', 'A529', 'mH', '0');

--tot domeniul 6 (Animale)
INSERT INTO INTREBARI VALUES('D6','Q56','Care este cel mai mare lucru pe care îl poate mânca o balen? albastr? dintr-o singur? înghi?itur? ?');
INSERT INTO RASPUNSURI VALUES ('Q56','A530','Nuca','0');
INSERT INTO RASPUNSURI VALUES ('Q56','A531','Grepfrut','1');
INSERT INTO RASPUNSURI VALUES ('Q56','A532','Un om','0');
INSERT INTO RASPUNSURI VALUES ('Q56','A533','O masina','0');
INSERT INTO RASPUNSURI VALUES ('Q56','A534','Un tir','0');
INSERT INTO RASPUNSURI VALUES ('Q56','A535','O barca','0');
INSERT INTO RASPUNSURI VALUES ('Q56','A536','O pisica de talie mare','0');
INSERT INTO RASPUNSURI VALUES ('Q56','A537','Un rechin','0');
INSERT INTO RASPUNSURI VALUES ('Q56','A538','O furnica','0');

--tot domeniul 11 geografie
INSERT INTO INTREBARI VALUES('D11','Q57','Care dintre urmatoarele locatii sunt state care apartin Statelor Unite ale Americii?');
INSERT INTO RASPUNSURI VALUES('Q57', 'A539', 'Georgia (New One)', '1');
INSERT INTO RASPUNSURI VALUES('Q57', 'A540', 'Georgia (Old One)', '0');
INSERT INTO RASPUNSURI VALUES('Q57', 'A541', 'Ontario', '0');
INSERT INTO RASPUNSURI VALUES('Q57', 'A542', 'Washington ', '1');
INSERT INTO RASPUNSURI VALUES('Q57', 'A543', 'Los Angeles', '0');
INSERT INTO RASPUNSURI VALUES('Q57', 'A544', 'Malibu', '0');
INSERT INTO RASPUNSURI VALUES('Q57', 'A545', 'California (We live in a)', '1');
INSERT INTO RASPUNSURI VALUES('Q57', 'A546', 'Kansas (Bottom Text)', '1');
INSERT INTO RASPUNSURI VALUES('Q57', 'A547', 'Arkansas ', '1');
INSERT INTO RASPUNSURI VALUES('Q57', 'A548', 'Regatul Unit al Marii Britanii si Irlandei de Nord', '0');

--tot domeniul 11 geografie
INSERT INTO INTREBARI VALUES('D11','Q58','Care este capitala prefecturii Tokyo?');
INSERT INTO RASPUNSURI VALUES('Q58', 'A549', 'Shinji', '0');
INSERT INTO RASPUNSURI VALUES('Q58', 'A550', 'Kazuma ', '0');
INSERT INTO RASPUNSURI VALUES('Q58', 'A551', 'Midoriya', '0');
INSERT INTO RASPUNSURI VALUES('Q58', 'A552', 'Madoka', '0');
INSERT INTO RASPUNSURI VALUES('Q58', 'A553', 'Niigato', '0');
INSERT INTO RASPUNSURI VALUES('Q58', 'A554', 'Nara', '0');
INSERT INTO RASPUNSURI VALUES('Q58', 'A555', 'Shinjuku', '1');
INSERT INTO RASPUNSURI VALUES('Q58', 'A556', 'Tottori', '0');
INSERT INTO RASPUNSURI VALUES('Q58', 'A557', 'Saitama', '0');
INSERT INTO RASPUNSURI VALUES('Q58', 'A558', 'Tsuyu', '0');

--Tot domeniul 11 (D11) Geografie
INSERT INTO INTREBARI VALUES('D11', 'Q59', 'Care din aceste judete apartine regiunii Dobrogea?');
INSERT INTO RASPUNSURI VALUES('Q59', 'A559', 'Tulcea', '1');
INSERT INTO RASPUNSURI VALUES('Q59', 'A560', 'Constanta', '1');
INSERT INTO RASPUNSURI VALUES('Q59', 'A561', 'Galati', '0');
INSERT INTO RASPUNSURI VALUES('Q59', 'A562', 'Braila', '0');
INSERT INTO RASPUNSURI VALUES('Q59', 'A563', 'Buzau', '0');
INSERT INTO RASPUNSURI VALUES('Q59', 'A564', 'Ialomita', '0');
INSERT INTO RASPUNSURI VALUES('Q59', 'A565', 'Calarasi', '0');
INSERT INTO RASPUNSURI VALUES('Q59', 'A566', 'Vrancea', '0');
INSERT INTO RASPUNSURI VALUES('Q59', 'A567', 'Giurgiu', '0');
INSERT INTO RASPUNSURI VALUES('Q59', 'A568', 'Iasi', '0');

INSERT INTO INTREBARI VALUES('D11', 'Q60', 'Care dintre urmatoarele atractii turistice se afla in Europa?');
INSERT INTO RASPUNSURI VALUES('Q60', 'A569', 'Central Park', '0');
INSERT INTO RASPUNSURI VALUES('Q60', 'A570', 'Colosseum', '1');
INSERT INTO RASPUNSURI VALUES('Q60', 'A571', 'Notre Dame', '1');
INSERT INTO RASPUNSURI VALUES('Q60', 'A572', 'Palas Mall', '1');
INSERT INTO RASPUNSURI VALUES('Q60', 'A573', 'Taj Mahal', '0');
INSERT INTO RASPUNSURI VALUES('Q60', 'A574', 'Turnul Eiffel', '1');
INSERT INTO RASPUNSURI VALUES('Q60', 'A575', 'Marele Zid Chinezesc', '0');
INSERT INTO RASPUNSURI VALUES('Q60', 'A576', 'Palatul Buckingham', '1');
INSERT INTO RASPUNSURI VALUES('Q60', 'A577', 'Burj Khalifa', '0');
INSERT INTO RASPUNSURI VALUES('Q60', 'A578', 'Parcul National al Marelui Canion', '0');

COMMIT;


create table teste(
    username varchar2(30) not null,
    intrebare int not null,
    q_id varchar2(8) not null,
    a_id_1 varchar2(8) not null,
    a_id_2 varchar2(8) not null,
    a_id_3 varchar2(8) not null,
    a_id_4 varchar2(8) not null,
    a_id_5 varchar2(8) not null,
    a_id_6 varchar2(8) not null,
    corect_a_ids varchar2(60) not null,
    user_a_ids varchar2(60)
)
/


create or replace procedure creare_test(username varchar2) as
    v_intrebare int;
    v_q_id intrebari.id%type;
    v_corect_a_id raspunsuri.id%type;
    v_poz_corect int;
    
    v_nr int;
    v_random int;
    v_contor int;
    
    -- tablou asociativ
    type map_int_int is table of int index by pls_integer;
    domenii_folosite map_int_int;
    v_domeniu intrebari.domeniu%type;
    
    type map_varchar_int is table of int index by raspunsuri.id%type;
    raspunsuri_folosite map_varchar_int;
    v_id_raspuns raspunsuri.id%type;
    
    -- tablou cu dimenisune variabila
    type varr is varray(6) of raspunsuri.id%type;
    v_a_ids varr;
    
    v_corect_a_ids teste.corect_a_ids%type;
    v_corect raspunsuri.corect%type;
    
    val_null teste.user_a_ids%type := null;
    
begin
    select count(distinct domeniu) into v_nr from intrebari;
    for v_intrebare in 1..10 loop
        -- cautam un domeniu neexplorat
        loop
            v_random := round(dbms_random.value(1, v_nr));
            exit when domenii_folosite.exists(v_random)=false;
        end loop;
        domenii_folosite(v_random) := v_intrebare;
        select domeniu into v_domeniu from (select domeniu, rownum rn from (select distinct domeniu from intrebari)) where rn=v_random;
        
        -- cautam o intrebare din acel domeniu
        select count(distinct id) into v_nr from intrebari where domeniu=v_domeniu;
        v_random := round(dbms_random.value(1, v_nr));
        select id into v_q_id from (select id, rownum rn from intrebari where domeniu=v_domeniu) where rn=v_random;
        
        -- selectam primul raspuns corect gasit
        select id into v_corect_a_id from raspunsuri where q_id=v_q_id and corect=1 and rownum=1;
        raspunsuri_folosite(v_corect_a_id) := 1;
        v_corect_a_ids := v_corect_a_id;
        
        -- selectam aleator alte 5 raspunsuri
        v_poz_corect := round(dbms_random.value(1,6));
        select count(id) into v_nr from raspunsuri where q_id=v_q_id;
        for v_contor in 2..6 loop
            loop
                v_random := round(dbms_random.value(1, v_nr));
                select id, corect into v_id_raspuns, v_corect from (select id, corect, rownum rn from raspunsuri where q_id=v_q_id) where rn=v_random;
                exit when raspunsuri_folosite.exists(v_id_raspuns)=false;
            end loop;
            if(v_poz_corect=v_contor) then
                raspunsuri_folosite(v_corect_a_id) := v_contor;
                raspunsuri_folosite(v_id_raspuns) := 1;
            else 
                raspunsuri_folosite(v_id_raspuns) := v_contor;
            end if;
            if(v_corect=1) then
                v_corect_a_ids := v_corect_a_ids||','||v_id_raspuns;
            end if;
        end loop;
        
        v_id_raspuns := raspunsuri_folosite.first;
        v_a_ids := varr();
        v_a_ids.extend(6);
        for v_contor in 1..6 loop
            v_a_ids(v_contor) := v_id_raspuns;
            if(v_contor<6) then
                v_id_raspuns := raspunsuri_folosite.next(v_id_raspuns);
            end if;
        end loop;
        
        insert into teste values (username,v_intrebare,v_q_id,v_a_ids(1),v_a_ids(2),v_a_ids(3),v_a_ids(4),v_a_ids(5),v_a_ids(6),v_corect_a_ids,val_null);
        raspunsuri_folosite.delete;
    end loop;
    commit;
end creare_test;


create or replace function urmatoarea_intrebare(p_username varchar2, p_raspuns varchar2) return varchar2 as
    v_exista_test number(1);
    v_q_text intrebari.text_intrebare%type;
    v_q_id intrebari.id%type;
    v_a_text raspunsuri.text_raspuns%type;
    v_a_id raspunsuri.id%type;
    v_contor int;
    v_intrebare int;
    
    v_a teste.user_a_ids%type;
    v_corect_a teste.corect_a_ids%type;
    
    type a_id is table of raspunsuri.id%type;
    v_user_a_ids a_id;
    v_corect_a_ids a_id;
    
    v_punctaj_partial number(4,2); -- punctaj pe un raspuns corect 
    v_punctaj_intrebare number(4,2);
    v_punctaj_total number(5,2) := 0;
    v_ok number(1);
    
    v_out varchar2(2000);
    
begin
    select count(distinct username) into v_exista_test from teste where username=p_username;
    if(v_exista_test=0) then
        creare_test(p_username);
        select q_id into v_q_id from teste where username=p_username and intrebare=1;
    else
        -- adaugam in tabela teste raspunsurile date de utilizator la intrebarea curenta
        v_q_id := substr(p_raspuns, 1, instr(p_raspuns, ',') - 1);
        v_a := substr(p_raspuns, instr(p_raspuns, ',') + 1);
        update teste set user_a_ids=v_a where username=p_username and q_id=v_q_id;
        commit;
        
        -- verificam daca intrebarea curenta este ultima din testul grila
        select intrebare into v_intrebare from teste where username=p_username and q_id=v_q_id;
        if(v_intrebare=10) then
            -- returnam punctajul final
            for v_contor in 1..10 loop
                v_user_a_ids := a_id();
                v_corect_a_ids := a_id();
                v_punctaj_intrebare := 0;
                
                -- raspunsurile date de utilizator la intrebarea v_contor + raspunsurile corecte la intrebarea v_contor
                select user_a_ids, corect_a_ids into v_a, v_corect_a from teste where username=p_username and intrebare=v_contor;
                
                -- punem raspunsurile date de utilizator intr-un nested table
                loop
                    exit when instr(v_a, ',')=0;
                    v_user_a_ids.extend;
                    v_user_a_ids(v_user_a_ids.count) := substr(v_a, 1, instr(v_a, ',') - 1);
                    v_a := substr(v_a, instr(v_a, ',') + 1);
                end loop;
                v_user_a_ids.extend;
                v_user_a_ids(v_user_a_ids.count) := v_a;
                -- punem raspunsurile corecte intr-un nested table
                loop
                    exit when instr(v_corect_a,',')=0;
                    v_corect_a_ids.extend;
                    v_corect_a_ids(v_corect_a_ids.count) := substr(v_corect_a, 1, instr(v_corect_a, ',') - 1);
                    v_corect_a := substr(v_corect_a, instr(v_corect_a, ',') + 1);
                end loop;
                v_corect_a_ids.extend;
                v_corect_a_ids(v_corect_a_ids.count) := v_corect_a;
                
                v_punctaj_partial := 10/v_corect_a_ids.count;
                
                for i in v_user_a_ids.first..v_user_a_ids.last loop
                    v_ok := 0;
                    for j in v_corect_a_ids.first..v_corect_a_ids.last loop
                        if(v_user_a_ids(i)=v_corect_a_ids(j)) then
                            v_punctaj_intrebare := v_punctaj_intrebare + v_punctaj_partial;
                            v_ok := 1;
                            exit;
                        end if;
                    end loop;
                    -- daca utilizatorul a bifat un raspuns gresit, scadem din punctaj
                    if(v_ok=0) then
                        v_punctaj_intrebare := v_punctaj_intrebare - v_punctaj_partial;
                    end if;
                end loop;
                
                if(v_punctaj_intrebare>0) then
                    v_punctaj_total := v_punctaj_total + v_punctaj_intrebare;
                end if;
            end loop;
            v_out := '{"Total":'||v_punctaj_total||'}';
            return v_out;
        else 
            select q_id into v_q_id from teste where username=p_username and intrebare=v_intrebare + 1;
        end if;
    end if;
    
    select text_intrebare into v_q_text from intrebari where id=v_q_id;
    v_out := '{"id_intrebare":"'||v_q_id||'", "intrebare":"'||v_q_text||'", ';
    for v_contor in 1..6 loop
        execute immediate ('select a_id_'||v_contor||' from teste where username=:1 and q_id=:2') into v_a_id using p_username, v_q_id;
        select text_raspuns into v_a_text from raspunsuri where id=v_a_id;
        v_out := v_out||'"id_rasp_'||v_contor||'":"'||v_a_id||'", "raspuns_'||v_contor||'":"'||v_a_text||'", ';
    end loop;
    v_out := v_out||'}';
    
    return v_out;
    
end urmatoarea_intrebare;
